### ISSUE TITLE
[Bug] Icon doesn't show when SukiSideMenu isn't expanded by default

### ISSUE THREAD

**Issue by Edgarianom1212** [kikipoulet/SukiUI#337] opened 2024-11-25 14:06 UTC
### Check the following items

- [X] I have looked up relevant Issue

### Description of the issue

When setting the property "IsMenuExpanded" of the SukiSideMenu to false in the axaml code, the icon doesn't show that is set for the currently selected SukiSideMenuItem.

### Package Version

6.0.0-rc

### Environment

Windows 10

### Expected Behavior

Icon should be visible even when having "IsMenuExpanded" set to false

### Reproduction

Set "IsMenuExpanded" to false in the axaml and set an icon for the SukiSideMenuItem that is currently showing

**Comment by Insire** [comment] 2024-12-06 19:00
You can set `IsSelectedItemContentMovable="False"` on the `SukiSideMenu` to circumvent the issue.

For actually attempting a fix, the following 3 styles in [SukiSideMenuItem.axaml](https://github.com/kikipoulet/SukiUI/blob/main/SukiUI/Controls/SukiSideMenuItem.axaml) seem to be the cause

- [1](https://github.com/kikipoulet/SukiUI/blob/main/SukiUI/Controls/SukiSideMenuItem.axaml#L100)
- [2](https://github.com/kikipoulet/SukiUI/blob/main/SukiUI/Controls/SukiSideMenuItem.axaml#L103)
- [3](https://github.com/kikipoulet/SukiUI/blob/main/SukiUI/Controls/SukiSideMenuItem.axaml#L106)

but im not sure why. removing them makes this work aswell, but obviously breaks the styling a bit. Maybe someone else can work this out.

**Comment by kikipoulet** [comment] 2024-12-11 12:03
fixed in [6ab83c6](https://github.com/kikipoulet/SukiUI/commit/6ab83c6f409267253be39bc59758707840a5ebd3)

**Closed by kikipoulet** 2024-12-11 12:03 UTC
